# Generated by Django 2.1.10 on 2019-07-17 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('blog', '0001_initial'), ('blog', '0002_auto_20190717_1721'), ('blog', '0003_auto_20190717_1722'), ('blog', '0004_auto_20190717_1733')]

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField()),
                ('markdown_content', models.TextField(blank=True)),
                ('html_content', models.TextField(blank=True)),
                ('published', models.BooleanField(default=False)),
                ('publish_date', models.DateTimeField(blank=True, null=True)),
                ('last_edit_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-publish_date'],
            },
        ),
    ]
